### ISSUE TITLE
Non Implemented Error

### ISSUE THREAD

**Issue by ryanjtaylor99** [adafruit/Adafruit_CircuitPython_BLE_Apple_Notification_Center#12]
When running the example code the error message below shows up. 

"NotImplementedError: Advertising not implemented"

I am attempting to run this code on a RaspberryPi 4B.

**Comment by tannewt** [comment]
I believe the Raspberry Pi only implements the central role (where it scans and initiates a connection.) The examples are a peripheral where they advertise and a phone connects to them. So, this isn't supported now by the examples. If you can figure out how to make a connection, then this library should work.
