### ISSUE TITLE
Reconnect error on Feather nRF52840 Express 

### ISSUE THREAD

**Issue by Kimpehzor** [adafruit/Adafruit_CircuitPython_BLE_Apple_Notification_Center#13]
I am running the sample "ble_apple_notification_center_new.py" on a Feather nRF52840 Express. The code runs without issue until I try reconnecting after:
1. I lose bluetooth signal
or
2. I restart my phone. 

This is the exception that is thrown when trying to reconnect after restarting the script:
**Traceback (most recent call last):
  File "code.py", line 33, in <module>
  File "adafruit_ble/__init__.py", line 88, in __getitem__
  File "adafruit_ble/__init__.py", line 52, in _discover_remote
ConnectionError: Connection has been disconnected and can no longer be used. Create a new connection.**

Restarting the script does not help. Disabling / Re-enabling bluetooth does not help. 

I have reproduced the issue using:
CircuitPython - 6.3.0 
CircuitPython - 7.0.0-alpha.6
iOS 14.7
iOS 15 Public Beta 5

The only temporary solution I have found so far is to unpair/re-pair the feather via iOS. This solves the issue until the next disconnect occurs.

**Comment by tannewt** [comment]
Closing this since it's documented here too: https://github.com/adafruit/Adafruit_CircuitPython_BLE/issues/130
