### ISSUE TITLE
esp32c3 board compatibility

### ISSUE THREAD

**Issue by biospank** [adafruit/Adafruit_CircuitPython_BLE_Apple_Notification_Center#18]
Hi,
I'm trying to run one of the examples (**ble_apple_notification_center_simpletest.py**) on a xiao esp32c3 board and I get this error:

`code.py output:
Waiting for connection
Connected
Traceback (most recent call last):
  File "code.py", line 27, in <module>
  File "adafruit_ble/__init__.py", line 91, in __contains__
  File "adafruit_ble/__init__.py", line 68, in _discover_remote
_bleio.BluetoothError: Unknown BLE error: 7
`
Board:
    [Seeed Studio XIAO ESP32C3](https://circuitpython.org/board/seeed_xiao_esp32c3/)
Version:
    Circuit Python: 8.1.0

Is the 'adafruit_ble' library only compatible on adafruit's boards?

**Comment by tannewt** [comment]
You'll have the best experience on an nRF52840.
